services:
  jobmanager:
    image: flink:2.2.0-java21
    hostname: jobmanager
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:2.2.0-java21
    hostname: taskmanager
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    # The parallelism of the job should be less than or equal to the number of task slots. Here we set to 16 (host CPU cores)
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 16

  sql-client:
    image: flink:2.2.0-java21
    hostname: sql-client
    container_name: sql-client
    depends_on:
      - jobmanager
    command: bin/sql-client.sh embedded
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
        rest.port: 8081
    tty: true
    stdin_open: true
